from pathlib import Path
ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'icon.png'

#sizing
BIG_FONT_SIZE= 40
MEDIUM_FONT_SIZE= 24
SMAL_FONT_SIZE= 18
TEXT_MARGIN = 15
MINIMUM_WIDTH = 600
BUTTON_SIZE = 65

# Colors
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'

